package demo5;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

/**
 * Test class made by ComTest
 * @version 2013.02.10 15:37:21 // Generated by ComTest
 *
 */
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testToString83 */
  @Test
  public void testToString83() {    // Pvm: 83
    Pvm pvm = new Pvm(10,2,2008); 
    assertEquals("From: Pvm line: 85", "10.2.2008", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse98 */
  @Test
  public void testParse98() {    // Pvm: 98
    Pvm pvm = new Pvm(); 
    pvm.parse("11.05.02"); assertEquals("From: Pvm line: 100", "11.5.2002", pvm.toString()); 
    pvm.parse("11.05.97"); assertEquals("From: Pvm line: 101", "11.5.1997", pvm.toString()); 
    pvm.parse("17.3"); assertEquals("From: Pvm line: 102", "17.3.1997", pvm.toString()); 
    pvm.parse("19"); assertEquals("From: Pvm line: 103", "19.3.1997", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPv135 */
  @Test
  public void testGetPv135() {    // Pvm: 135
    Pvm pvm = new Pvm(); 
    pvm.parse("12.1.1995"); 
    assertEquals("From: Pvm line: 138", 12, pvm.getPv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKk148 */
  @Test
  public void testGetKk148() {    // Pvm: 148
    Pvm pvm = new Pvm(); 
    pvm.parse("12.1.1995"); 
    assertEquals("From: Pvm line: 151", 1, pvm.getKk()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetV161 */
  @Test
  public void testGetV161() {    // Pvm: 161
    Pvm pvm = new Pvm(); 
    pvm.parse("12.1.1995"); 
    assertEquals("From: Pvm line: 164", 1995, pvm.getV()); 
  } // Generated by ComTest END
}