package d7;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d7.Kirjeenpaino.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.24 17:00:15 // Generated by ComTest
 *
 */
public class KirjeenpainoTest {



  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPaino23 */
  @Test
  public void testSuurinKirjeenPaino23() {    // Kirjeenpaino: 23
    assertEquals("From: Kirjeenpaino line: 24", 50, suurinKirjeenPaino(0.60)); 
    assertEquals("From: Kirjeenpaino line: 25", 50, suurinKirjeenPaino(0.70)); 
    assertEquals("From: Kirjeenpaino line: 26", 100, suurinKirjeenPaino(0.90)); 
    assertEquals("From: Kirjeenpaino line: 27", 0, suurinKirjeenPaino(0.20)); 
    assertEquals("From: Kirjeenpaino line: 28", 2000, suurinKirjeenPaino(10.0)); 
    assertEquals("From: Kirjeenpaino line: 29", 500, suurinKirjeenPaino(2.20)); 
  } // Generated by ComTest END
}