package d7;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d7.Palindromi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.24 17:48:20 // Generated by ComTest
 *
 */
public class PalindromiTest {



  // Generated by ComTest BEGIN
  /** testPalindromi26 */
  @Test
  public void testPalindromi26() {    // Palindromi: 26
    assertEquals("From: Palindromi line: 27", true, palindromi("maoam"));
    assertEquals("From: Palindromi line: 28", true, palindromi("lol"));
    assertEquals("From: Palindromi line: 29", true, palindromi("ammma"));
    assertEquals("From: Palindromi line: 30", false, palindromi("apua"));
    assertEquals("From: Palindromi line: 31", true, palindromi(""));
    assertEquals("From: Palindromi line: 32", false, palindromi("pelle"));
    assertEquals("From: Palindromi line: 33", true, palindromi("gogog"));
    assertEquals("From: Palindromi line: 34", true, palindromi("MaoAm"));
  } // Generated by ComTest END
}