package d7;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d7.Tuhoa.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.24 17:23:30 // Generated by ComTest
 *
 */
public class TuhoaTest {



  // Generated by ComTest BEGIN
  /** testTuhoaLopusta26 */
  @Test
  public void testTuhoaLopusta26() {    // Tuhoa: 26
    StringBuilder s = new StringBuilder("Kissa naukuu"); 
    assertEquals("From: Tuhoa line: 28", "Kissa n", tuhoaLopusta(s,5));
    assertEquals("From: Tuhoa line: 29", "Kiss", tuhoaLopusta(s,3));
    assertEquals("From: Tuhoa line: 30", "K", tuhoaLopusta(s,3));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTuhoaLopusta48 */
  @Test
  public void testTuhoaLopusta48() {    // Tuhoa: 48
    String s = "Miten menee?"; 
    assertEquals("From: Tuhoa line: 50", "Miten mene", tuhoaLopusta(s,2));
    assertEquals("From: Tuhoa line: 51", "Miten ", tuhoaLopusta(s,6));
    assertEquals("From: Tuhoa line: 52", "Miten menee", tuhoaLopusta(s,1));
  } // Generated by ComTest END
}