package paketti4;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static paketti4.Tarkkuus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.02 11:36:42 // Generated by ComTest
 *
 */
public class TarkkuusTest {



  // Generated by ComTest BEGIN
  /** testEtumerkki28 */
  @Test
  public void testEtumerkki28() {    // Tarkkuus: 28
    assertEquals("From: Tarkkuus line: 29", -1, etumerkki(-1, 0.0000001)); 
    assertEquals("From: Tarkkuus line: 30", 0, etumerkki(0, 0.0000001)); 
    assertEquals("From: Tarkkuus line: 31", -1, etumerkki(-0.000003, 0.0000001)); 
    assertEquals("From: Tarkkuus line: 32", 1, etumerkki(0.00001, 0.0000001)); 
    assertEquals("From: Tarkkuus line: 33", 0, etumerkki(-0.0000000000001, 0.0000001)); 
  } // Generated by ComTest END
}