package demo2;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo2.Kolmio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.01 15:48:08 // Generated by ComTest
 *
 */
public class KolmioTest {



  // Generated by ComTest BEGIN
  /** testKolmionAla30 */
  @Test
  public void testKolmionAla30() {    // Kolmio: 30
    assertEquals("From: Kolmio line: 31", 12.5, kolmionAla(5,5), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHypotenuusa45 */
  @Test
  public void testHypotenuusa45() {    // Kolmio: 45
    assertEquals("From: Kolmio line: 47", 11.18, hypotenuusa(10,5), 0.01); 
    assertEquals("From: Kolmio line: 48", 11.18, hypotenuusa(10,5), 0.01); 
    assertEquals("From: Kolmio line: 49", 11.18, hypotenuusa(10,5), 0.01); 
  } // Generated by ComTest END
}