package paketti5;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static paketti5.Demopisteet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.02 12:57:04 // Generated by ComTest
 *
 */
public class DemopisteetTest {



  // Generated by ComTest BEGIN
  /** testHyvityspisteet24 */
  @Test
  public void testHyvityspisteet24() {    // Demopisteet: 24
    assertEquals("From: Demopisteet line: 25", 6, hyvityspisteet(96)); 
    assertEquals("From: Demopisteet line: 26", 5, hyvityspisteet(80)); 
    assertEquals("From: Demopisteet line: 27", 2, hyvityspisteet(50)); 
    assertEquals("From: Demopisteet line: 28", 3, hyvityspisteet(60)); 
    assertEquals("From: Demopisteet line: 29", 0, hyvityspisteet(10)); 
    assertEquals("From: Demopisteet line: 30", 5, hyvityspisteet(85)); 
    assertEquals("From: Demopisteet line: 31", 4, hyvityspisteet(76)); 
  } // Generated by ComTest END
}