package d9;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

/**
 * Test class made by ComTest
 * @version 2013.03.06 12:54:58 // Generated by ComTest
 *
 */
public class EhdokasTest {



  // Generated by ComTest BEGIN
  /** testMain85 */
  @Test
  public void testMain85() {    // Ehdokas: 85
    Ehdokas ehd3 = new Ehdokas(100.0, 0); 
    assertEquals("From: Ehdokas line: 87", 100.0, ehd3.getRaha(), 0.000001);
    assertEquals("From: Ehdokas line: 88", 0, ehd3.getAanet());
    ehd3.setRaha(10000.0); 
    assertEquals("From: Ehdokas line: 90", 10000.0, ehd3.getRaha(), 0.000001);
    ehd3.setAanet(5000); 
    assertEquals("From: Ehdokas line: 92", 5000, ehd3.getAanet());
    Ehdokas ehd4 = new Ehdokas(1000.0, 100000); 
    assertEquals("From: Ehdokas line: 94", 95000, ehd4.compareTo(ehd3));
  } // Generated by ComTest END
}