package d9;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d9.PisinNouseva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.03.07 14:34:09 // Generated by ComTest
 *
 */
public class PisinNousevaTest {



  // Generated by ComTest BEGIN
  /** testPisinNouseva33 */
  @Test
  public void testPisinNouseva33() {    // PisinNouseva: 33
    String a1 = "abajiuxac"; 
    assertEquals("From: PisinNouseva line: 35", 3, pisinNouseva(a1));
    String a2 = "kissa"; 
    assertEquals("From: PisinNouseva line: 37", 3, pisinNouseva(a2));
    String a3 = "abcdefg"; 
    assertEquals("From: PisinNouseva line: 39", 7, pisinNouseva(a3));
  } // Generated by ComTest END
}