package d9;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

/**
 * Test class made by ComTest
 * @version 2013.03.06 16:11:52 // Generated by ComTest
 *
 */
public class TaulukkoTest {



  // Generated by ComTest BEGIN
  /** 
   * testTaulukko8 
   * @throws Taulukko.TaulukkoTaysiException when error
   */
  @Test
  public void testTaulukko8() throws Taulukko.TaulukkoTaysiException {    // Taulukko: 8
    Taulukko luvut = new Taulukko(); 
    luvut.lisaa(0); luvut.lisaa(2); luvut.lisaa(99); 
    assertEquals("From: Taulukko line: 12", "0,2,99", luvut.toString()); 
    luvut.set(1,4); assertEquals("From: Taulukko line: 13", "0,4,99", luvut.toString()); 
    int luku = luvut.get(2); 
    assertEquals("From: Taulukko line: 15", 99, luku); 
    assertEquals("From: Taulukko line: 16", 99, luvut.get(2)); 
    try {
    luvut.set(21, 4); 
    fail("Taulukko: 17 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    luvut.lisaa(0); luvut.lisaa(0);  //taulukko täyteen
    try {
    luvut.lisaa(0); 
    fail("Taulukko: 19 Did not throw Taulukko.TaulukkoTaysiException");
    } catch(Taulukko.TaulukkoTaysiException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testMain119 
   * @throws Taulukko.TaulukkoTaysiException when error
   */
  @Test
  public void testMain119() throws Taulukko.TaulukkoTaysiException {    // Taulukko: 119
    Taulukko lukuja = new Taulukko(10); 
    lukuja.lisaa(5); 
    lukuja.lisaa(6); 
    Taulukko lukuja1 = lukuja.clone(); 
    lukuja.lisaa(7); 
    assertEquals("From: Taulukko line: 126", "5,6", lukuja1.toString());
    Taulukko luvut1 = new Taulukko(10); 
    luvut1.lisaa(1); 
    luvut1.lisaa(2); 
    luvut1.lisaa(3); 
    luvut1.lisaa(3); 
    luvut1.lisaa(6); 
    luvut1.lisaa(6); 
    luvut1.lisaa(8); 
    luvut1.lisaa(9); 
    luvut1.poista(1); 
    assertEquals("From: Taulukko line: 137", "2,3,3,6,6,8,9", luvut1.toString()); 
  } // Generated by ComTest END
}