package d6;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d6.Pvm.*;

/**
 * Test class made by ComTest
 * @version 2013.02.18 11:30:50 // Generated by ComTest
 *
 */
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testToString136 */
  @Test
  public void testToString136() {    // Pvm: 136
    Pvm tammi2011 = new Pvm(1,1,2011); 
    assertEquals("From: Pvm line: 138", "1.1.2011", tammi2011.toString());
    Pvm helmi2011 = new Pvm(1,2,2011); 
    assertEquals("From: Pvm line: 140", "1.2.2011", helmi2011.toString());
    Pvm tanaan = new Pvm(14,2,2011); 
    assertEquals("From: Pvm line: 142", "14.2.2011", tanaan.toString());
    Pvm maalis97 = new Pvm(1,3,1997); 
    assertEquals("From: Pvm line: 144", "1.3.1997", maalis97.toString());
    Pvm paiva = new Pvm(30,2,2012); 
    assertEquals("From: Pvm line: 146", "13.2.2012", paiva.toString());
    Pvm paiva2 = new Pvm(30,2,0); 
    assertEquals("From: Pvm line: 148", "13.2.2012", paiva2.toString());
    Pvm paiva3 = new Pvm(100,100,2013); 
    assertEquals("From: Pvm line: 150", "13.2.2013", paiva3.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse189 */
  @Test
  public void testParse189() {    // Pvm: 189
    Pvm pvm = new Pvm(11,3,2003); 
    pvm.parse("12"); assertEquals("From: Pvm line: 191", "12.3.2003", pvm.toString()); 
    pvm.parse("..2001"); assertEquals("From: Pvm line: 192", "12.3.2001", pvm.toString()); 
    pvm.parse("..2009 14:30"); assertEquals("From: Pvm line: 193", "12.3.2009", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse208 */
  @Test
  public void testParse208() {    // Pvm: 208
    Pvm pvm = new Pvm(11,3,2003); 
    StringBuilder jono = new StringBuilder("12"); 
    pvm.parse(jono); assertEquals("From: Pvm line: 211", "12.3.2003", pvm.toString()); assertEquals("From: Pvm line: 211", "", jono.toString()); 
    jono = new StringBuilder("..2001"); 
    pvm.parse(jono); assertEquals("From: Pvm line: 213", "12.3.2001", pvm.toString()); assertEquals("From: Pvm line: 213", "", jono.toString()); 
    jono = new StringBuilder("..2009 14:30"); 
    pvm.parse(jono); assertEquals("From: Pvm line: 215", "12.3.2009", pvm.toString()); assertEquals("From: Pvm line: 215", "14:30", jono.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPv228 */
  @Test
  public void testGetPv228() {    // Pvm: 228
    Pvm pv = new Pvm("14.2.2011"); 
    assertEquals("From: Pvm line: 230", 14, pv.getPv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKk241 */
  @Test
  public void testGetKk241() {    // Pvm: 241
    Pvm pv = new Pvm("14.2.2011"); 
    assertEquals("From: Pvm line: 243", 2, pv.getKk()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVv254 */
  @Test
  public void testGetVv254() {    // Pvm: 254
    Pvm pv = new Pvm("14.2.2011"); 
    assertEquals("From: Pvm line: 256", 2011, pv.getVv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo289 */
  @Test
  public void testCompareTo289() {    // Pvm: 289
    Pvm p10 = new Pvm(21,2,1876); 
    Pvm p11 = new Pvm(21,2,1875); 
    assertEquals("From: Pvm line: 292", 1, p10.compareTo(p11));
    Pvm p12 = new Pvm(20,2,1876); 
    Pvm p13 = new Pvm(21,2,1876); 
    assertEquals("From: Pvm line: 295", -1, p12.compareTo(p13));
    Pvm p14 = new Pvm(21,2,1876); 
    Pvm p15 = new Pvm(21,2,1876); 
    assertEquals("From: Pvm line: 298", 0, p14.compareTo(p15));
    Pvm p16 = new Pvm(21,3,2012); 
    Pvm p17 = new Pvm(21,2,2012); 
    assertEquals("From: Pvm line: 301", 1, p16.compareTo(p17));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals324 */
  @Test
  public void testEquals324() {    // Pvm: 324
    Pvm pp1 = new Pvm(21,2,1875); 
    Pvm pp2 = new Pvm(21,2,1875); 
    assertEquals("From: Pvm line: 327", true, pp1.equals(pp2));
    Pvm pp3 = new Pvm(20,2,1876); 
    Pvm pp4 = new Pvm(21,2,1876); 
    assertEquals("From: Pvm line: 330", false, pp3.equals(pp4));
    Pvm pp5 = new Pvm(21,2,1876); 
    Pvm pp6 = new Pvm(21,2,1876); 
    assertEquals("From: Pvm line: 333", true, pp5.equals(pp6));
    Pvm pp7 = new Pvm(21,3,2012); 
    Pvm pp8 = new Pvm(21,2,2012); 
    assertEquals("From: Pvm line: 336", false, pp7.equals(pp8));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo350 */
  @Test
  public void testCompareTo350() {    // Pvm: 350
    Pvm p1 = new Pvm(21,2,1876); 
    Pvm p2 = new Pvm(21,2,1875); 
    assertEquals("From: Pvm line: 353", 1, compareTo(p1,p2));
    Pvm p3 = new Pvm(20,2,1876); 
    Pvm p4 = new Pvm(21,2,1876); 
    assertEquals("From: Pvm line: 356", -1, compareTo(p3,p4));
    Pvm p5 = new Pvm(21,2,1876); 
    Pvm p6 = new Pvm(21,2,1876); 
    assertEquals("From: Pvm line: 359", 0, compareTo(p5,p6));
    Pvm p7 = new Pvm(21,3,2012); 
    Pvm p8 = new Pvm(21,2,2012); 
    assertEquals("From: Pvm line: 362", 1, compareTo(p7,p8));
  } // Generated by ComTest END
}