package d6;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d6.Taulukot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.18 11:09:08 // Generated by ComTest
 *
 */
public class TaulukotTest {



  // Generated by ComTest BEGIN
  /** testPienin32 */
  @Test
  public void testPienin32() {    // Taulukot: 32
    int kPituudet[] = { 30,28,30,30,30,30,31,31,30,31,30,31} ; 
    assertEquals("From: Taulukot line: 34", 28, pienin(kPituudet));
    int kPituudet1[] = { 1,28,14,30,30,30,31,31,30,31,30,31} ; 
    assertEquals("From: Taulukot line: 36", 1, pienin(kPituudet1));
    int kPituudet2[] = { 30,8,14,30,30,30,31,31,30,31,30,31} ; 
    assertEquals("From: Taulukot line: 38", 8, pienin(kPituudet2));
    int kPituudet3[] = { 30,28,14,30,30,30,31,31,13,31,30,31} ; 
    assertEquals("From: Taulukot line: 40", 13, pienin(kPituudet3));
    int kPituudet4[] = { 30,28,30,30,30,15,31,31,30,31,30,31} ; 
    assertEquals("From: Taulukot line: 42", 15, pienin(kPituudet4));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPienimmanPaikka55 */
  @Test
  public void testPienimmanPaikka55() {    // Taulukot: 55
    int kPituudet[] = { 30,28,31,30,30,30,31,31,30,31,30,31} ; 
    assertEquals("From: Taulukot line: 57", 1, pienimmanPaikka(kPituudet));
    int kPituudet1[] = { 30,28,14,30,30,30,31,31,30,31,30,31} ; 
    assertEquals("From: Taulukot line: 59", 2, pienimmanPaikka(kPituudet1));
    int kPituudet2[] = { 30,28,14,30,30,30,31,31,30,31,30,1} ; 
    assertEquals("From: Taulukot line: 61", 11, pienimmanPaikka(kPituudet2));
  } // Generated by ComTest END
}