package d8;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static d8.MatriisinSumma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.27 11:15:04 // Generated by ComTest
 *
 */
public class MatriisinSummaTest {



  // Generated by ComTest BEGIN
  /** testMatriisinSumma27 */
  @Test
  public void testMatriisinSumma27() {    // MatriisinSumma: 27
    double[][] matriisi1 = new double[][]{ { 1,6,3,4,8} , { 6,7,8,9,10} } ; 
    assertEquals("From: MatriisinSumma line: 29", 62, matriisinSumma(matriisi1), 0.000001);
    double[][] matriisi2 = new double[][]{ { 1,6,3,4,8} , { 6,7,8,9,0} } ; 
    assertEquals("From: MatriisinSumma line: 31", 52, matriisinSumma(matriisi2), 0.000001);
    double[][] matriisi3 = new double[][]{ { 1,100,3,4,8} , { 6,7,8,9,10} } ; 
    assertEquals("From: MatriisinSumma line: 33", 156, matriisinSumma(matriisi3), 0.000001);
    double[][] matriisi4 = new double[][]{ { 0.5,6,3,4,8} , { 6,7,8,9,10} } ; 
    assertEquals("From: MatriisinSumma line: 35", 61.5, matriisinSumma(matriisi4), 0.000001);
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma50 */
  @Test
  public void testSumma50() {    // MatriisinSumma: 50
    double[] taulukko1 = new double[]{ 1,2,3,4,5,6} ; 
    assertEquals("From: MatriisinSumma line: 52", 21, summa(taulukko1), 0.000001);
    double[] taulukko2 = new double[]{ 1,2,3,4,5,3.5} ; 
    assertEquals("From: MatriisinSumma line: 54", 18.5, summa(taulukko2), 0.000001);
    double[] taulukko3 = new double[]{ 0,2,3,4,5,6} ; 
    assertEquals("From: MatriisinSumma line: 56", 20, summa(taulukko3), 0.000001);
    double[] taulukko4 = new double[]{ 1,2,3,100,5,6} ; 
    assertEquals("From: MatriisinSumma line: 58", 117, summa(taulukko4), 0.000001);
  } // Generated by ComTest END
}