package paketti1;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static paketti1.Automaatti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.02.02 12:09:22 // Generated by ComTest
 *
 */
public class AutomaattiTest {



  // Generated by ComTest BEGIN
  /** testAutomaatti26 */
  @Test
  public void testAutomaatti26() {    // Automaatti: 26
    assertEquals("From: Automaatti line: 27", false, automaatti("010010")); 
    assertEquals("From: Automaatti line: 28", true, automaatti("01001")); 
    assertEquals("From: Automaatti line: 29", false, automaatti("01010101")); 
    assertEquals("From: Automaatti line: 30", true, automaatti("")); 
    assertEquals("From: Automaatti line: 31", false, automaatti("01")); 
    assertEquals("From: Automaatti line: 32", false, automaatti("01000")); 
    assertEquals("From: Automaatti line: 33", true, automaatti("0100")); 
    assertEquals("From: Automaatti line: 34", true, automaatti("000000")); 
    assertEquals("From: Automaatti line: 35", false, automaatti("111110")); 
  } // Generated by ComTest END
}