package teht2;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static teht2.Merkkijono.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.01.28 11:25:33 // Generated by ComTest
 *
 */
public class MerkkijonoTest {



  // Generated by ComTest BEGIN
  /** testOnkoSamatKysymysmerkilla30 */
  @Test
  public void testOnkoSamatKysymysmerkilla30() {    // Merkkijono: 30
    assertEquals("From: Merkkijono line: 31", true, onkoSamatKysymysmerkilla("Kissa","K?ss?")); 
    assertEquals("From: Merkkijono line: 32", true, onkoSamatKysymysmerkilla("Kissa","K????")); 
    assertEquals("From: Merkkijono line: 33", true, onkoSamatKysymysmerkilla("Kissa","Kissa")); 
    assertEquals("From: Merkkijono line: 34", false, onkoSamatKysymysmerkilla("Kassa","K?ssi")); 
  } // Generated by ComTest END
}