package d10;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.io.IOException;
import static org.junit.Assert.*;
import org.junit.*;
import static d10.KirjaintenEsiintymat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.03.14 09:10:56 // Generated by ComTest
 *
 */
public class KirjaintenEsiintymatTest {



  // Generated by ComTest BEGIN
  /** 
   * testMain23 
   * @throws IOException when error
   */
  @Test
  public void testMain23() throws IOException {    // KirjaintenEsiintymat: 23
    VertaaTiedosto.kirjoitaTiedosto("hiljaa.txt",
    "aaaaa\n"+
    "bbbbb\n"+
    "ccccc\n"+
    "kkkkk\n"); 
    String tulos =
    "a: 5\n"+
    "b: 5\n"+
    "c: 5\n"+
    "k: 5\n"; 
    VertaaTiedosto.tuhoaTiedosto("tulos.txt"); 
    main(new String[]{"hiljaa.txt","tulos.txt"}); 
    assertEquals("From: KirjaintenEsiintymat line: 41", null, VertaaTiedosto.vertaaFileString("tulos.txt",tulos)); 
    VertaaTiedosto.tuhoaTiedosto("tulos.txt"); 
    VertaaTiedosto.tuhoaTiedosto("hiljaa.txt"); 
  } // Generated by ComTest END
}