package d10;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.io.IOException;
import static org.junit.Assert.*;
import org.junit.*;
import static d10.TietytRivit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2013.03.14 09:08:55 // Generated by ComTest
 *
 */
public class TietytRivitTest {



  // Generated by ComTest BEGIN
  /** 
   * testMain23 
   * @throws IOException when error
   */
  @Test
  public void testMain23() throws IOException {    // TietytRivit: 23
    VertaaTiedosto.kirjoitaTiedosto("hiljaa.txt",
    "** hiljaa 1 hiipii\n"+
    "hyv‰ 33 tulee\n"+
    "** 1 3 5 55\n"+
    "nyt 33 riitt‰‰\n"); 
    String tulos =
    "** hiljaa 1 hiipii\n"+
    "** 1 3 5 55\n"; 
    VertaaTiedosto.tuhoaTiedosto("tulos.txt"); 
    main(new String[]{"hiljaa.txt","tulos.txt"}); 
    assertEquals("From: TietytRivit line: 39", null, VertaaTiedosto.vertaaFileString("tulos.txt",tulos)); 
    VertaaTiedosto.tuhoaTiedosto("tulos.txt"); 
    VertaaTiedosto.tuhoaTiedosto("hiljaa.txt"); 
  } // Generated by ComTest END
}